#!/bin/sh

set -e

# empty message of the day.
#echo -n > /etc/motd

# remove some unused packages
#DEBIAN_FRONTEND=noninteractive apt-get purge -y laptop-detect tasksel emacsen-common ienglish-common ispell

# install some additional packages
#DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends linux-headers-amd64 openssh-server sudo time openssl gnutls-bin zip unzip bzip2 lynx vim vim-scripts curl whois net-tools patch telnet sqlite3 strace lsof less screen rsync git git-lfs dos2unix myrepos traceroute bash-completion socat busybox psmisc man-db dnsutils unattended-upgrades gpg-agent gnupg software-properties-common tcpdump make gzrt jq bash zsh htop dbus-user-session fuse3 acl python3-venv python3-pip python3-setuptools python3-wheel python3-psutil python3-pylibacl python3-sh python3-prometheus-client rdiff-backup xfsprogs smartmontools

# members of `sudo` group are not asked for password.
#sed -i 's/^%sudo\tALL=(ALL:ALL) ALL/%sudo\tALL=(ALL:ALL) NOPASSWD:ALL/' /etc/sudoers

# new users should be put into the "users" group
#sed -i 's/^USERGROUPS=yes/USERGROUPS=no/' /etc/adduser.conf

# fix the time server configuration
#sed -i 's/^#NTP=/NTP=us.pool.ntp.org/' /etc/systemd/timesyncd.conf

# unpack the postinstall tar file
tar -z -x -C /tmp -f /tmp/postinstall.tar.gz

# install global things and root things
#mkdir -m700 -p /root/.ssh
#cp /tmp/postinstall.d/resolv.conf /etc/resolv.conf
#cp /tmp/postinstall.d/apt.conf.d/50unattended-upgrades /etc/apt/apt.conf.d/50unattended-upgrades
#cp /tmp/postinstall.d/apt.conf.d/20auto-upgrades /etc/apt/apt.conf.d/20auto-upgrades
#cp /tmp/postinstall.d/vimrc /root/.vimrc
#cp /tmp/postinstall.d/bash_login /root/.bash_login

# When VMWare Fusion first boots the .iso image, a virtual ethernet
# card is assigned to the virtual pci slot 33
# Based on the the idea of "predictable names", the assigned interface
# name in linux is ens33. The debian installer builds the networking setup on
# this name.
# See: https://wiki.debian.org/NetworkInterfaceNames#initrd
# The assigned pci slot is part of the VMware virtual machine and is noted
# in the .vmx file with the attribute
#
#       ethernet0.pcislotnumber = 33
#
# Vagrant will ignore this setup and assign a new pci slot 160
# This results in a new ethernet device name ens160. Therefore the 
# networking code will not work anymore as the interface name ens33 is
# noted in /etc/network/interfaces.
# The plan is to disable the "predictable names" and have the oldfashioned
# "eth0" back during install. This can be achieved by disabling 
#
# /lib/systemd/network/99-default.link
#
# which is responsible for the "predictable" name.
# Therefore we overwrite this by putting a file in /etc
cp /tmp/postinstall.d/99-default.link /etc/systemd/network/

# install ssh keys and other things for paul user
mkdir -m700 -p /home/caeuser/.ssh
cp /tmp/postinstall.d/authorized_keys /home/caeuser/.ssh/authorized_keys
cp /tmp/postinstall.d/vimrc /home/caeuser/.vimrc
#cp /tmp/postinstall.d/bash_login /home/paul/.bash_login

# install ssh keys such that user vagrant can login without password
# This are the vagrant non secure public keys which are used by vagrant
mkdir -m700 -p /home/vagrant/.ssh
cp /tmp/postinstall.d/authorized_keys /home/vagrant/.ssh/authorized_keys
chown -R vagrant:vagrant /home/vagrant
chmod 700 /home/vagrant
chmod 600 /home/vagrant/.ssh/authorized_keys
# vagrant can do sudo without password
cp /tmp/postinstall.d/sudoers /etc/sudoers.d/vagrant
chmod 400 /etc/sudoers.d/vagrant
