- name: Disable sudo password
  hosts: myhosts
  tasks:
    - name: Copy nopasswd to /etc/sudoers.d
      ansible.builtin.copy:
        src: files/sudo-nopass
        dest: /etc/sudoers.d
      become: true