- name: My first play
  hosts: default
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:
   
   - name: Print message
     ansible.builtin.debug:
      msg: Hello world

- name: Disable sudo password
  ansible.builtin.import_playbook: disable-sudo-password.yaml

- name: Install KDE Desktop Environment
  hosts: default
  tasks:
   - name: Install KDE Plasma Desktop
     ansible.builtin.apt:
      name: kde-plasma-desktop
     become: true
     when: 0 > 1

- name: Install LXQt Desktop Environment
  hosts: default
  tasks:
   - name: Install LXQt Desktop
     ansible.builtin.apt:
      name: lxqt-core
     become: true
     when: 0 > 1


- name: Install UTM guest tools
  hosts: default
  tasks:
   - name: Install UTM guest tools
     ansible.builtin.apt:
      name: spice-vdagent
            , qemu-guest-agent
     become: true
     when: 0 > 1

- name: Install VMware guest tools
  hosts: default
  tasks:
    - name: Install VMWare guest tools
      ansible.builtin.apt:
        name: open-vm-tools-desktop
      become: true

- name: Reboot
  hosts: default
  tasks:
    - name: Reboot
      ansible.builtin.command: shutdown -r now
      become: true
      when: 0 > 1

- name: HiDPI Settings
  hosts: default
  tasks:
    - name: Set Cursor Size
      ansible.builtin.lineinfile:
        path: ~/.Xresources
        regexp: '^Xcursor\.size:*'
        line: 'Xcursor.size: 128'
        create: yes
    - name: Set Font DPI
      ansible.builtin.lineinfile:
        path: ~/.Xresources
        regexp: '^Xft\.dpi:*'
        line: 'Xft.dpi: 192'
        create: yes
    - name: Append GDK_SCALE to .bashrc
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        regexp: '^export GDK_SCALE=*'
        line: 'export GDK_SCALE=2'
        create: yes
    - name: Append GDK_DPI_SCALE to .bashrc
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        regexp: '^export GDK_DPI_SCALE=*'
        line: 'export GDK_DPI_SCALE=0.5'
        create: yes

- name: Lightdm Autologin
  ansible.builtin.import_playbook: autologin-lightdm.yaml

- name: Install VS Codium
  ansible.builtin.import_playbook: vscodium.yaml

- name: Install GHDL + GtkWave
  ansible.builtin.import_playbook: ghdl.yaml
