- name: Install Quartus FPGA Software via debian package
  hosts: default
  tasks:
    - name: Add quartus repository 
      ansible.builtin.copy:
        src: ../quartus-debian-package/quartus.list
        dest: /etc/apt/sources.list.d
      become: true
    - name: Install Quartus
      ansible.builtin.apt:
        update_cache: true
        name: quartus13
      become: true
    - name: Append quartuspath to PATH in .bashrc
      ansible.builtin.lineinfile:
        path: $HOME/.bashrc
        regexp: "^export PATH=$PATH:/opt/altera/13.0sp1/quartus/bin"
        line: "export PATH=$PATH:/opt/altera/13.0sp1/quartus/bin"
      become: '{{ ansible_user_id == "vagrant" }}'
      become_user: caeuser
