- name: Install LXQt Desktop Environment
  hosts: default
  tasks:
    - name: Install LXQt Desktop
      ansible.builtin.apt:
        update_cache: yes
        name: lxqt-core, lightdm
      become: true

- name: Lightdm Autologin
  ansible.builtin.import_playbook: autologin-lightdm.yaml

- name: Install VS Codium
  ansible.builtin.import_playbook: vscodium.yaml

- name: Install Quartus
  ansible.builtin.import_playbook: quartus-package.yaml

- name: Reboot
  hosts: default
  tasks:
    - name: Reboot
      ansible.builtin.command: shutdown -r now
      become: true

