- name: Install LXQt Desktop Environment
  hosts: default
  tasks:
    - name: Install LXQt Desktop
      ansible.builtin.apt:
        update_cache: yes
        name: lxqt-core, lightdm
      become: true

- name: Lightdm Autologin
  ansible.builtin.import_playbook: autologin-lightdm.yaml

- name: Install UTM guest tools when on UTM
  hosts: default
  tasks:
    - name: Show virtualization environment
      ansible.builtin.debug:
        var: ansible_virtualization_type
    - name: Install UTM guest tools
      ansible.builtin.apt:
        name: spice-vdagent
              , qemu-guest-agent
      become: true
      when: ansible_virtualization_type == "kvm"

- name: Install VS Codium
  ansible.builtin.import_playbook: vscodium.yaml

- name: Install Quartus
  ansible.builtin.import_playbook: quartus-package.yaml

- name: Reboot
  hosts: default
  tasks:
    - name: Reboot
      ansible.builtin.command: shutdown -r now
      become: true

